services:
  web:
    build:
      context: ./ticketbooking
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/var/lib/web/staticfiles
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export MIGRATE=0 &&
        python manage.py migrate &&
        export MIGRATE=1 &&
        python manage.py collectstatic --noinput && 
        gunicorn ticketbooking.wsgi:application --bind 0.0.0.0:9000",
      ]
    port:
      - "127:0.0.1:9000:9000"
    env_file:
      - .env.hosting
    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.hosting.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "superuser", "-d", "bookmyticket"]
    

volumes:
  postgres_data:
  static_volume: