services:
  web:
    build:
      context: ./ticketbooking
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export MIGRATE=0 &&
        python manage.py migrate &&
        export MIGRATE=1 &&
        python manage.py collectstatic --noinput && 
        gunicorn ticketbooking.wsgi:application --bind 0.0.0.0:8000",
      ]
    expose:
      - 8000
    env_file:
      - .env.hosting
    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.hosting.db
      
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    env_file:
      - .env.hosting

  certbot:
    build:
      context: ./certbot
    command: echo "Skipping..."
    env_file:
      - .env.hosting
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
  postgres_data:
  static_volume: