services:
  web:
    build:
      context: ./ticketbooking
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export MIGRATE=0 &&
        python manage.py migrate &&
        export MIGRATE=1 &&
        python manage.py collectstatic --noinput && 
        gunicorn ticketbooking.wsgi:application --bind 0.0.0.0:8000",
      ]
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:

