services:
  web:
    build: ./ticketbooking
    command: /bin/bash -c "
                    export MIGRATE=0 &&
                    python manage.py migrate &&
                    export MIGRATE=1 &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ticketbooking:/usr/src/ticketbooking/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bookmyticket

volumes:
  postgres_data:
