# Generated by Django 5.1.2 on 2024-10-21 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('aid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('verification_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_address', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=13)),
                ('contact_email', models.EmailField(max_length=254)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('walletid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transcation', models.BinaryField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='foods',
            fields=[
                ('foodID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('itemname', models.CharField(help_text='Enter item name: ', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter item price: ', max_digits=5)),
                ('availibilty', models.BooleanField()),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.admin')),
            ],
        ),
        migrations.CreateModel(
            name='shows',
            fields=[
                ('showID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('movie', models.CharField(help_text='Enter a movie name: ', max_length=255)),
                ('type', models.CharField(help_text='Enter movie viewing type (2D/3D etc): ', max_length=20)),
                ('language', models.CharField(help_text='Enter movie language: ', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('seats', models.BinaryField(max_length=2000)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.admin')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('shows', models.BinaryField(max_length=2000)),
                ('food', models.BinaryField(max_length=2000)),
                ('walletid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='transcations',
            fields=[
                ('transcationsID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('R', 'Reverted'), ('C', 'Completed')], default='I', max_length=1)),
                ('receivingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='catalog.wallet')),
                ('sendingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='catalog.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='walletid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.wallet'),
        ),
    ]
