# Generated by Django 5.1.2 on 2024-10-24 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='movieID',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieID',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
