# Generated by Django 5.1.2 on 2024-10-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='adminuser',
        ),
        migrations.RenameModel(
            old_name='transcations',
            new_name='transactions',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transcationsID',
            new_name='transactionsID',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='transcation',
            new_name='transaction',
        ),
    ]
