# Generated by Django 5.1.2 on 2024-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.CharField(default='UA', max_length=5),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(help_text='Enter movie viewing type: ', max_length=20),
        ),
    ]
