# Generated by Django 5.1.2 on 2024-10-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='seats',
        ),
    ]
