# Generated by Django 5.1.2 on 2024-10-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_shows_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
