# Generated by Django 5.1.2 on 2024-10-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_admin_adminuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='contact_address',
            new_name='theater_address',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='contact_email',
            new_name='theater_email',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='contact_name',
            new_name='theater_name',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='contact_phone',
            new_name='theater_phone',
        ),
    ]
