# Generated by Django 5.1.2 on 2024-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_movies_rating_alter_movies_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='theater_address',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='theater_name',
            field=models.CharField(help_text='Enter theater name and address: ', max_length=200, unique=True),
        ),
    ]
