# Generated by Django 5.1.2 on 2024-10-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_contact_address_adminuser_theater_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='type',
        ),
    ]
