# Generated by Django 5.1.2 on 2024-10-24 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_movies_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movieID',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
