# Generated by Django 5.1.2 on 2024-10-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_movieid_movies_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='seats_booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foods',
            name='itemname',
            field=models.CharField(help_text='Enter item name: ', max_length=255, unique=True),
        ),
    ]
