# Generated by Django 5.1.2 on 2024-10-27 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_user_email_remove_user_food_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='foodID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('ticketID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.foods')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.shows')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
    ]
