# Generated by Django 5.1.2 on 2024-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_tickets_food_alter_tickets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
