# Generated by Django 5.1.2 on 2024-11-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.transactions'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0b383a', max_length=6),
        ),
    ]
