# Generated by Django 5.1.2 on 2024-11-07 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_tickets_transaction_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f6a7ed', max_length=6),
        ),
        migrations.CreateModel(
            name='foodorder',
            fields=[
                ('orderID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.foods')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tickets')),
            ],
        ),
    ]
