# Generated by Django 5.1.2 on 2024-11-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'permissions': (('theateradmin', 'User is theater admin'),)},
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='ebf921', max_length=6),
        ),
    ]
