# Generated by Django 5.1.2 on 2024-11-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='tp_created_at',
            new_name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(max_length=6),
        ),
    ]
