# Generated by Django 5.1.2 on 2024-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_adminuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='availibilty',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0bfe11', max_length=6),
        ),
    ]
