# Generated by Django 5.1.2 on 2024-11-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_foods_availibilty_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='itemname',
            field=models.CharField(help_text='Enter item name: ', max_length=255),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4f34ee', max_length=6),
        ),
    ]
