# Generated by Django 5.1.2 on 2024-11-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_foods_itemname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='status',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='verified',
            field=models.BooleanField(default=0),
        ),
    ]
