# Generated by Django 5.1.2 on 2024-11-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_foodorder_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='bound',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='old_verified',
            field=models.BooleanField(default=0),
        ),
    ]
